# Generated by Django 4.2.6 on 2023-10-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_categoria_projeto_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='descricao',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='url',
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.categoria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pequena_descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.cliente'),
        ),
    ]
