# Generated by Django 4.2.6 on 2023-10-08 16:11

from ckeditor.fields import RichTextField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cliente_rename_descricao_projeto_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='conteudo',
            field=RichTextField(),
        ),
    ]
